name: Notify Blog
on:
  push:
    branches: [master]
    paths-ignore:
      - '.obsidian/**'
      - '.github/**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BLOG_REPO_TOKEN }}
          repository: R1pplon/blog
          event-type: note-updated